### ISSUE TITLE
Periodic Notes feature

### ISSUE THREAD

**Issue by ff2400t** [Feel-ix-343/markdown-oxide#157]
I wanted to have a feature based on this extension https://github.com/liamcain/obsidian-periodic-notes
You can have a command for Weekly or Monthly Note the it will open or create a file for that period's note. So when calling the command this week it will open one dated `Weekly/30 29-7-2024.md` in the configured folder.
You should maybe have it configured like so
```toml
[weekly-note]
folder = "weekly/"
template_file = "templates/weekly.md"
file_name_format = "%U %d-%m-%Y"
```
Same format can work for Monthly Notes. You can generalize this for daily notes so that all of them use similar format like this

**Comment by Feel-ix-343** [comment]
Thank you for the suggestion!

I am thinking of a response, but I like it.

**Comment by Feel-ix-343** [comment]
Hey, I don't think this is in scope for the near future. 

Perhaps down the line in v1 it can be revisited.

**Comment by ff2400t** [comment]
@Feel-ix-343 would you be willing a accept a PR for this?

**Comment by Feel-ix-343** [comment]
Yes sure that would be great!

**Comment by Kxnr** [comment]
@ff2400t you're welcome to take from/build off of my branch [here](https://github.com/Kxnr/markdown-oxide/tree/notebooks-config)--I've added some ability to configure notebooks as:

```toml
[notebooks.journal]
folder = "/home/kxnr/wiki/journal"
note_format = "%Y-%u"

[notebooks.monthly]
folder = "/home/kxnr/wiki/monthly"
note_format = "month_%m"
```

there some aspects that would need to change to contribute back (I pulled out some completions, changed around some commands, and it's utterly undocumented, for a start), but is along the lines you suggested.
