### ISSUE TITLE
Parse code blocks

### ISSUE THREAD

**Issue by Feel-ix-343** [Feel-ix-343/markdown-oxide#7]
related to #6

**Comment by chenlijun99** [comment]
Have you ever thought about using tree-sitter for parsing markdown?
https://github.com/tree-sitter-grammars/tree-sitter-markdown seems to support also Obsidian wikilinks and tags.

**Comment by chenlijun99** [comment]
Oh, never mind. Just came across this Reddit post of yours (https://www.reddit.com/r/neovim/comments/1306suu/general_recommendations_should_i_use_treesitter).
Also saw in the git history that you were using tree-sitter, for then for some reason it has been abandoned.

**Comment by Feel-ix-343** [comment]
I have certainly been thinking about this. I used regex instead of treesitter because the initial parse time was near instant while treesitter would take seconds, and because it was plain easy. I am sure I will be able to parse code blocks using regex, but some major features I want in the future rely on parsing indented lists (semantic search!!! and true, Logseq style indexed blocks!!), so the regex can only take me so far. 

It will requite a lot of implementation to do the treesitter parsing, and I haven't found a use for it in the immediate future. However, certainly this LS will have its own parser or use treesitter.

**Comment by dawsers** [comment]
There is another bug related to this. Any code block that contains something looking like a tag

``` sh
#!/usr/bin/bash
cd ~
```

generates a tag in the database.

Maybe it would be a good idea to skip code blocks. In my opinion, references or tags in a code block maybe should be put outside, otherwise you would need to parse for a lot more than markdown, basically any language, and consider possibilities like having `[]` inside a code block, etc.

My initial comment in #6 was related to this. At that point, `markdown-oxide` was unable to detect code blocks, so it was generating tags for cases like the above. Now, it can detect them, so it would be very easy to simply ignore anything inside a code block.

**Comment by Feel-ix-343** [comment]
Hey!

You should be able to disable this in settings. Check the readme.

There are cases like obsidian dataview where parsing tags and links in code blocks is helpful, so I left it on by default.

What do you think about this?

**Comment by dawsers** [comment]
This is my settings.toml

``` toml
# Leave blank to try to import from Obsidian Daily Notes
# Formatting from https://docs.rs/chrono/latest/chrono/format/strftime/index.html
dailynote = "%Y-%m-%d" # this is akin to YYYY-MM-DD from Obsidian

# Fuzzy match file headings in completions
heading_completions = true

# Set true if you title your notes by the first heading
# Right now, if true this will cause completing a file link in the markdown style
# to insert the name of the first heading in the display text area
# [](file) -> [first heading of file.md](file)
# If false, [](file) -> [](file) (for example)
title_headings = true

# Show diagnostics for unresolved links; note that even if this is turned off,
# special semantic tokens will be sent for the unresolved links, allowing you
# to visually identify unresolved links
unresolved_diagnostics = true

semantic_tokens = false

# Resolve tags in code blocks
tags_in_codeblocks = false
# Resolve references in code blocks
references_in_codeblocks = false
```

so I think it is disabled.
